# Generated by Django 5.0.3 on 2024-04-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Название категории', max_length=100)),
                ('description', models.TextField(db_column='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Таблица категорий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Название', max_length=100)),
                ('description', models.TextField(db_column='Описание')),
                ('img_product', models.ImageField(blank=True, db_column='Картинка (превью)', null=True, upload_to='img_product/')),
                ('price', models.FloatField(db_column='   Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='Дата последнего изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'Таблица продуктов',
            },
        ),
    ]
